// Auto-generated by Convex. Replace with real output by running `npx convex dev`.
export const api: any = new Proxy(
  {},
  {
    get: (_target, _prop) =>
      new Proxy(
        {},
        {
          get: () => (_args: any) => undefined,
        }
      ),
  }
);
