// Auto-generated by Convex. Replace with real output by running `npx convex dev`.
import { query as _query, mutation as _mutation } from "convex/server";
export const query = _query;
export const mutation = _mutation;
